/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lacysKioskGUIparts;

import javax.swing.JOptionPane;
import lacysKioskLogicparts.Inventory;
import lacysKioskLogicparts.Products;
import lacysKioskLogicparts.ShoppingCart;
import lacysKioskLogicparts.ShoppingCartItem;

/**
 *
 * @author Alisha
 */
public class AddToCartPopUp extends javax.swing.JInternalFrame {

    Products product; //Variable to hold product for pop up
    
    /**
     * Creates new form AddToCartPopUp
     */
    public AddToCartPopUp() {
        initComponents();
        setVisible(false); //Not visible until needed
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLabel = new javax.swing.JLabel();
        addItemNameLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        inventoryLabel = new javax.swing.JLabel();
        confirmAddCartButton = new javax.swing.JButton();
        addCartCancelButton = new javax.swing.JButton();
        quantityTextField = new javax.swing.JTextField();

        setTitle("Add Item To Cart");

        addLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addLabel.setText("ADD: ");

        addItemNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addItemNameLabel.setText("Product Name Here");

        quantityLabel.setText("Quantity: ");

        priceLabel.setText("Price: $X.XX");

        totalLabel.setText("Total: $X.XX");

        inventoryLabel.setText("Inventory: XX");

        confirmAddCartButton.setText("Confirm");
        confirmAddCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddCartButtonActionPerformed(evt);
            }
        });

        addCartCancelButton.setText("Cancel");
        addCartCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCartCancelButtonActionPerformed(evt);
            }
        });

        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quantityLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(confirmAddCartButton)))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addCartCancelButton)
                                    .addComponent(inventoryLabel))))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addItemNameLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(addLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addItemNameLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(inventoryLabel)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmAddCartButton)
                    .addComponent(addCartCancelButton))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmAddCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddCartButtonActionPerformed
        //Add the product to user's cart and close pop up window
        ShoppingCart aCart = MainPage.getCart();
        boolean added = false;
        int num = Integer.parseInt(quantityTextField.getText()); //Get quantity in case user changed number
        if (aCart.getCart().containsKey(product.getProductID()))
        {
            String addMsg = "That item is already in your cart. Update quantities from your cart view.";
            JOptionPane.showMessageDialog(null, addMsg,"Already In Cart", JOptionPane.ERROR_MESSAGE);
        }
        else if (num > 1)
        {
            aCart.addMultipleItems(product.getProductID(), product, num);
            added = true;
        }
        else if (num == 1)
        {
            aCart.addItem(product.getProductID(), product);
            added = true;
        }
        else 
        {
            String addMsg = "There is nothing to add to your cart.";
            JOptionPane.showMessageDialog(null, addMsg,"No Product", JOptionPane.ERROR_MESSAGE);
        }
        //If an item was added, Add to cart list for table on cart card
        if (added)
        {
            MainPage.addToCartList(new ShoppingCartItem(product, Integer.parseInt(quantityTextField.getText())));
            HeaderPanel.setNumInCartLabel(MainPage.getCart().getNumItems()); //update cart amount number in header
        }
        setVisible(false); //make this popup not visible again
    }//GEN-LAST:event_confirmAddCartButtonActionPerformed

    private void addCartCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCartCancelButtonActionPerformed
        //Close the pop up window but don't add product to cart
        setVisible(false);
    }//GEN-LAST:event_addCartCancelButtonActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        //If user enters new value in text field and presses enter, update the total amount label
        totalLabel.setText(String.format("Total: $%,.2f", product.getUnitPrice() * Integer.parseInt(quantityTextField.getText())));
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    public void setUpAddPopUp(Products prod) //Sets up the pop up window with the correct product info
    {
        product = prod;
        addItemNameLabel.setText("ADD: " + product.getProductName());
        quantityTextField.setText("1");
        inventoryLabel.setText(String.format("Current Inventory: %d", product.getUnitsInStock()));
        priceLabel.setText(String.format("Price: $%,.2f", product.getUnitPrice()));
        totalLabel.setText(String.format("Total: $%,.2f", product.getUnitPrice() * Integer.parseInt(quantityTextField.getText())));   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCartCancelButton;
    private javax.swing.JLabel addItemNameLabel;
    private javax.swing.JLabel addLabel;
    private javax.swing.JButton confirmAddCartButton;
    private javax.swing.JLabel inventoryLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
