
package lacysKioskGUIparts;

import java.awt.CardLayout;
import lacysKioskLogicparts.Users;

/**
 * Header panel for logging in, 2 cards it switches between whether logged in or logged out
 * @author Alisha
 */
public class HeaderPanel extends javax.swing.JPanel {
    
    //Since this panel mostly is in charge of log in, it will hold the variable of if user is logged in or not
    static boolean loggedIn = false;
    
    /**
     * Creates new form HeaderPanel
     */
    public HeaderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstHeaderPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        cartLabel = new javax.swing.JLabel();
        cartItemNumText = new javax.swing.JTextField();
        userNameText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        secondHeaderPanel = new javax.swing.JPanel();
        cartLabel1 = new javax.swing.JLabel();
        cartItemNumText1 = new javax.swing.JTextField();
        logOutButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();

        setName("theHeaderPnl"); // NOI18N
        setLayout(new java.awt.CardLayout());

        userNameLabel.setLabelFor(userNameText);
        userNameLabel.setText("Username");

        logInButton.setText("Log In");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        cartLabel.setLabelFor(cartItemNumText);
        cartLabel.setText("My Cart");

        cartItemNumText.setEditable(false);
        cartItemNumText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cartItemNumText.setText("(0)");
        cartItemNumText.setToolTipText("");
        cartItemNumText.setBorder(null);
        cartItemNumText.setDisabledTextColor(new java.awt.Color(240, 240, 240));

        userNameText.setToolTipText("");

        passwordLabel.setLabelFor(passwordText);
        passwordLabel.setText("Password");

        javax.swing.GroupLayout firstHeaderPanelLayout = new javax.swing.GroupLayout(firstHeaderPanel);
        firstHeaderPanel.setLayout(firstHeaderPanelLayout);
        firstHeaderPanelLayout.setHorizontalGroup(
            firstHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(cartLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartItemNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        firstHeaderPanelLayout.setVerticalGroup(
            firstHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logInButton)
                    .addComponent(cartLabel)
                    .addComponent(cartItemNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(firstHeaderPanel, "NotLoggedInCard");

        cartLabel1.setLabelFor(cartItemNumText);
        cartLabel1.setText("My Cart");

        cartItemNumText1.setEditable(false);
        cartItemNumText1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cartItemNumText1.setText("(0)");
        cartItemNumText1.setToolTipText("");
        cartItemNumText1.setBorder(null);

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setText("Welcome, ");

        userLabel.setText("current user");

        javax.swing.GroupLayout secondHeaderPanelLayout = new javax.swing.GroupLayout(secondHeaderPanel);
        secondHeaderPanel.setLayout(secondHeaderPanelLayout);
        secondHeaderPanelLayout.setHorizontalGroup(
            secondHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondHeaderPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(welcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLabel)
                .addGap(68, 68, 68)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(cartLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartItemNumText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        secondHeaderPanelLayout.setVerticalGroup(
            secondHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondHeaderPanelLayout.createSequentialGroup()
                        .addGroup(secondHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cartLabel1)
                            .addComponent(cartItemNumText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondHeaderPanelLayout.createSequentialGroup()
                        .addGroup(secondHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logOutButton)
                            .addComponent(welcomeLabel)
                            .addComponent(userLabel))
                        .addContainerGap())))
        );

        add(secondHeaderPanel, "LoggedInCard");

        getAccessibleContext().setAccessibleName("theHeaderPnl");
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed

        String name = userNameText.getText();
        String pswd = String.valueOf(passwordText.getPassword());
        
        if (MainPage.getEManager().login(name, pswd))
        {
            Users user = MainPage.getEManager().findUser(name);
            MainPage.setUser(user); //Set user value on main page
            CardLayout cl = (CardLayout)(this.getLayout());
            cl.show(this, "LoggedInCard"); //flipped to logged in header card
            userLabel.setText(name); //set user's name in welcome message
            loggedIn = true;
            MainPage.setProductButtons(loggedIn);
            //Set something here to check if there are items in cart and ask user if would like to keep items
            //or if would like to clear cart. In case they had been browsing as a guest and now want to sign in
            //and keep what they might have already added.
        }
        userNameText.setText(""); //clear fields
        passwordText.setText("");

    }//GEN-LAST:event_logInButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        
        CardLayout cl = (CardLayout) (this.getLayout());
        cl.show(this, "NotLoggedInCard"); //Go back to logged out header card
        loggedIn = false; 
        MainPage.setProductButtons(loggedIn);
        MainPage.setUser(null);
        MainPage.clearCart(); //clear cart
        setNumInCartLabel(0); //set the cart number label back to zero
    }//GEN-LAST:event_logOutButtonActionPerformed

    public static void setNumInCartLabel(int num) //This needs to be accessed by other classes
    {
        if (loggedIn)
        {
            cartItemNumText1.setText(String.format("(%d)", num));
        }
        else
        {
            cartItemNumText.setText(String.format("(%d)", num));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField cartItemNumText;
    private static javax.swing.JTextField cartItemNumText1;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JLabel cartLabel1;
    private javax.swing.JPanel firstHeaderPanel;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JPanel secondHeaderPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameText;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
