/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lacysKioskGUIparts;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.ListIterator;
import javax.swing.BoxLayout;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import lacysKioskLogicparts.Account;
import lacysKioskLogicparts.Inventory;
import lacysKioskLogicparts.LacysEntityManager;
import lacysKioskLogicparts.ShoppingCart;
import lacysKioskLogicparts.ShoppingCartItem;
import lacysKioskLogicparts.Users;

/**
 *
 * @author Alisha
 */
public class MainPage extends javax.swing.JFrame {

    public static final String JDBC_DRIVER = "org.sqlite.JDBC";
    public static final String DATABASE_URL = "jdbc:sqlite:C:\\Data\\lacys"; 
    private static Account user = new Account(); //Testing user until switch to entity class version
    private static Users currentUser = new Users(); //Holds the current user in the system
    private static ShoppingCart cart = new ShoppingCart();  //Holds shopping cart for user
    private static DefaultTableModel cartModel; //This is the model to go with the cart table
    private static AddToCartPopUp addCart; //This popup window confirms adding an item to cart
    private static CheckReviewsPopUp checkReviews; //This popup window shows product reviews
    private static LacysEntityManager eManager; //Class to handle inventory requests
    
    private Connection connection; //Temporary while using regular database stuff
    private Statement statement; //Temporary while using regular database stuff
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        eManager = new LacysEntityManager();
        cartModel = (DefaultTableModel)cartTable.getModel();
        addCart = new AddToCartPopUp();
        checkReviews = new CheckReviewsPopUp();
       
        desktop.add(addCart);
        desktop.add(checkReviews);
        try
		{
			// load database driver class
			Class.forName(JDBC_DRIVER);
			// connect to database
			connection = DriverManager.getConnection(DATABASE_URL);

			// create statement to query database
			statement = connection.createStatement();
			// query the database and get the result set
			
			// now setup a display
		}

		catch (SQLException sqle)
		{
			JOptionPane.showMessageDialog(null, sqle.getMessage(),"Database Error", JOptionPane.ERROR_MESSAGE);
			sqle.printStackTrace();
			System.exit(1);
		}

		catch (ClassNotFoundException cnfe)
		{
			JOptionPane.showMessageDialog(null,cnfe.getMessage(),"Driver not Found", JOptionPane.ERROR_MESSAGE);
			System.exit(1);
		}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        leftSidePanel = new javax.swing.JPanel();
        pagesLabel = new javax.swing.JLabel();
        pagesBoxLabel = new javax.swing.JLabel();
        pagesComboBox = new javax.swing.JComboBox();
        rightSidePanel = new javax.swing.JPanel();
        shoppingLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        categoryBoxLabel = new javax.swing.JLabel();
        middlePanel = new javax.swing.JPanel();
        homePagePanel = new javax.swing.JPanel();
        storeNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackText = new javax.swing.JTextArea();
        feedbackSubmitButton = new javax.swing.JButton();
        feedbackLabel = new javax.swing.JLabel();
        productViewPanel = new javax.swing.JPanel();
        newAccountPanel = new javax.swing.JPanel();
        newAccountLabel = new javax.swing.JLabel();
        newUsernameLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel2 = new javax.swing.JLabel();
        newUsernameText = new javax.swing.JTextField();
        newPasswordText = new javax.swing.JPasswordField();
        newPasswordText2 = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        cartPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        checkOutButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        orderPanel = new javax.swing.JPanel();
        orderLabel = new javax.swing.JLabel();
        shippingComboBox = new javax.swing.JComboBox();
        subTotalLabel = new javax.swing.JLabel();
        shipCostLabel = new javax.swing.JLabel();
        taxesLabel = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        orderCancelButton = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsTextArea = new javax.swing.JTextArea();
        headerPanel2 = new lacysKioskGUIparts.HeaderPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lacy's Kiosk Application");

        leftSidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        leftSidePanel.setMaximumSize(new java.awt.Dimension(300, 32767));
        leftSidePanel.setPreferredSize(new java.awt.Dimension(125, 458));

        pagesLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagesLabel.setText("Pages");

        pagesBoxLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pagesBoxLabel.setText("Go To:");

        pagesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main", "Create Account", "My Cart", "My Account" }));
        pagesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagesBoxLabel)
                            .addComponent(pagesLabel)))
                    .addGroup(leftSidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pagesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pagesLabel)
                .addGap(18, 18, 18)
                .addComponent(pagesBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pagesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightSidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rightSidePanel.setMaximumSize(new java.awt.Dimension(300, 32767));

        shoppingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shoppingLabel.setText("Shopping");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Home", "Clothes", "Kitchen" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        categoryBoxLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        categoryBoxLabel.setText("Browse Category:");

        javax.swing.GroupLayout rightSidePanelLayout = new javax.swing.GroupLayout(rightSidePanel);
        rightSidePanel.setLayout(rightSidePanelLayout);
        rightSidePanelLayout.setHorizontalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rightSidePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightSidePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(shoppingLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSidePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categoryBoxLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightSidePanelLayout.setVerticalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(shoppingLabel)
                .addGap(28, 28, 28)
                .addComponent(categoryBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        middlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middlePanel.setPreferredSize(new java.awt.Dimension(438, 458));
        middlePanel.setLayout(new java.awt.CardLayout());

        storeNameLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        storeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storeNameLabel.setText("Lacy's");
        storeNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        storeNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("image goes here");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("image goes here");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackText.setColumns(20);
        feedbackText.setRows(5);
        jScrollPane1.setViewportView(feedbackText);

        feedbackSubmitButton.setText("Submit");
        feedbackSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackSubmitButtonActionPerformed(evt);
            }
        });

        feedbackLabel.setLabelFor(feedbackText);
        feedbackLabel.setText("Provide Feedback: ");

        javax.swing.GroupLayout homePagePanelLayout = new javax.swing.GroupLayout(homePagePanel);
        homePagePanel.setLayout(homePagePanelLayout);
        homePagePanelLayout.setHorizontalGroup(
            homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePagePanelLayout.createSequentialGroup()
                .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePagePanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(feedbackSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePagePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedbackLabel)
                            .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(homePagePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addComponent(storeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        homePagePanelLayout.setVerticalGroup(
            homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePagePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(storeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(feedbackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        middlePanel.add(homePagePanel, "homePanelCard");

        javax.swing.GroupLayout productViewPanelLayout = new javax.swing.GroupLayout(productViewPanel);
        productViewPanel.setLayout(productViewPanelLayout);
        productViewPanelLayout.setHorizontalGroup(
            productViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        productViewPanelLayout.setVerticalGroup(
            productViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        middlePanel.add(productViewPanel, "productsCard");

        newAccountLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newAccountLabel.setText("New Account");

        newUsernameLabel.setLabelFor(newUsernameText);
        newUsernameLabel.setText("Enter Username: ");

        newPasswordLabel.setLabelFor(newPasswordText);
        newPasswordLabel.setText("Enter Password: ");

        newPasswordLabel2.setLabelFor(newPasswordText2);
        newPasswordLabel2.setText("Re-enter Password:");

        createButton.setText("Create Account");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newAccountPanelLayout = new javax.swing.GroupLayout(newAccountPanel);
        newAccountPanel.setLayout(newAccountPanelLayout);
        newAccountPanelLayout.setHorizontalGroup(
            newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAccountPanelLayout.createSequentialGroup()
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAccountPanelLayout.createSequentialGroup()
                        .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAccountPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(newUsernameLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newPasswordLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createButton)
                            .addComponent(newUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordText2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newAccountPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(newPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newAccountPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(newAccountLabel)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        newAccountPanelLayout.setVerticalGroup(
            newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAccountPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(newAccountLabel)
                .addGap(52, 52, 52)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUsernameLabel)
                    .addComponent(newUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLabel))
                .addGap(46, 46, 46)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLabel2))
                .addGap(42, 42, 42)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        middlePanel.add(newAccountPanel, "newAccountCard");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("My Cart");

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Price", "Total", "Remove"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setName(""); // NOI18N
        jScrollPane2.setViewportView(cartTable);

        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Cart");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalLabel.setText("Total: $##.##");

        updateButton.setText("Update Cart");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton))
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(totalLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(checkOutButton)
                .addGap(44, 44, 44)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addGap(18, 18, 18)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutButton)
                    .addComponent(clearButton))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        middlePanel.add(cartPanel, "cartCard");

        orderPanel.setPreferredSize(new java.awt.Dimension(432, 458));

        orderLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        orderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderLabel.setText("Order");

        shippingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add Shipping", "Ship to Store - Free", "Ship to Home - $10.00" }));
        shippingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingComboBoxActionPerformed(evt);
            }
        });

        subTotalLabel.setText("Subtotal: $#.##");

        shipCostLabel.setText("Shipping: $#.##");

        taxesLabel.setText("Taxes: $#.##");

        grandTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grandTotalLabel.setText("Total: $#.##");

        jLabel8.setText("Credit card number:");

        jLabel9.setText("Expiration date: ");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("xx/xxxx");

        jLabel10.setText("Enter name: ");

        jLabel11.setText("Enter street address:");

        jLabel12.setText("Enter city:");

        jLabel13.setText("Enter state:");

        jLabel14.setText("Enter Zip Code:");

        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        orderCancelButton.setText("Cancel");
        orderCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCancelButtonActionPerformed(evt);
            }
        });

        itemsTextArea.setColumns(20);
        itemsTextArea.setRows(5);
        jScrollPane3.setViewportView(itemsTextArea);

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(orderLabel))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(placeOrderButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5)))))
                .addContainerGap())
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taxesLabel)
                                    .addComponent(subTotalLabel)
                                    .addComponent(shipCostLabel)
                                    .addComponent(grandTotalLabel)))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(shippingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderCancelButton)
                                    .addGroup(orderPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shippingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grandTotalLabel)
                .addGap(18, 18, 18)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeOrderButton)
                    .addComponent(orderCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        middlePanel.add(orderPanel, "orderCard");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        desktop.setLayer(leftSidePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(rightSidePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(middlePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(headerPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pagesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesComboBoxActionPerformed
        //From the combo box on the left, go to specific pages/cards in card layout of middle panel
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        String selectedPage = (String)pagesComboBox.getSelectedItem();
        
        if (selectedPage.equals("Main"))
        {
            cl.show(middlePanel, "homePanelCard");
        }
        else if (selectedPage.equals("Create Account"))
        {
            cl.show(middlePanel, "newAccountCard");
        }
        else if (selectedPage.equals("My Cart"))
        {
            cl.show(middlePanel, "cartCard");
            totalLabel.setText(String.format("Total: $%,.2f", cart.getTotal()));
            changeHeader();
        }
        
    }//GEN-LAST:event_pagesComboBoxActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        //When click check out button, go to check out page/card
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        cl.show(middlePanel, "orderCard");
        
        String orderText = "";
        orderText = "        Item Name                    Quantity        Price           Total Price\n";
        orderText += "-----------------------------------  -------------     -----------     -----------------\n";
        for (int i = 0; i < cartModel.getRowCount (); i++)
        {
            String name = cartModel.getValueAt(i, 0).toString();
            int amount = (int) cartModel.getValueAt(i, 1);
            double price = (double) cartModel.getValueAt(i, 2);
            orderText += String.format("%-45s  %-16d  $%-12.2f  %-12.2f\n", name, amount, price, amount * price);
        }
        itemsTextArea.setText(orderText);
        subTotalLabel.setText(String.format("Subtotal: $%.2f", cart.getTotal()));
        taxesLabel.setText(String.format("Sales Tax: $%.2f", cart.getTotal() * cart.getSalesTax()));  //Hard coded sales tax rate in
        shipCostLabel.setText(String.format("Shipping Cost: $%.2f", 0.00));
        grandTotalLabel.setText(String.format("Total:     $%.2f", cart.calcGrandTotal()));
        cart.setShipCost(0.00);

    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        //Go through actions to create new user and add to database
       
    }//GEN-LAST:event_createButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        //Checks if any checkboxes are checked or unchecked and then deletes the ones
        //that are checked from cart
        ArrayList<Integer> rowNums = new ArrayList<Integer>(); //holds row numbers that need to be deleted
        int numRows = cartModel.getRowCount();
        for (int row = 0; row < numRows; row++)
        {
            String prodName = cartModel.getValueAt(row, 0).toString();
            Inventory product = eManager.findProductbyName(prodName);
            if ((boolean) cartModel.getValueAt(row, 4) || (int) cartModel.getValueAt(row, 1) == 0)
            {
                //remove row from cart table list and cart map
                if (product != null)
                {
                    cart.removeItem(product.getItemID());
                    //cartModel.removeRow(row);
                    rowNums.add(row);
                }
            }
            else
            {
                //get object info from cart and update cart map
                if (product != null)
                {
                    cart.updateItem(product.getItemID(), (int) cartModel.getValueAt(row, 1));
                    cartModel.setValueAt((int) cartModel.getValueAt(row, 1) * (double) cartModel.getValueAt(row, 2) , row, 3);
                }
                
            }
        
        }
        
        //Go backwards so if deleting multiple rows from table, it won't affect later row numbers
        for (int i = rowNums.size() - 1; i >= 0; i--)  
        {
            cartModel.removeRow(rowNums.get(i));
        }
        cartModel.fireTableDataChanged();
        totalLabel.setText(String.format("Total: $%,.2f", cart.getTotal()));
        changeHeader();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        //This button will clear all the items currently in the cart and return to the home page maybe?
        int numRows = cartModel.getRowCount();
        for (int i = numRows - 1; i >= 0; i--)
        {   
            cartModel.removeRow(i);
        }
        cartModel.fireTableDataChanged();
        cart.clear();
        totalLabel.setText(String.format("Total: $%,.2f", cart.getTotal()));
        changeHeader();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void shippingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingComboBoxActionPerformed
        String shipChoice = shippingComboBox.getSelectedItem().toString();
        if (shipChoice.equals("Ship to Store - Free"))
        {
            cart.setShipCost(0.00);
            shipCostLabel.setText(String.format("Shipping Cost: $%.2f", cart.getShipCost()));
            grandTotalLabel.setText(String.format("Total:     $%.2f", cart.calcGrandTotal()));
        }
        else if (shipChoice.equals("Ship to Home - $10.00"))
        {
            cart.setShipCost(10.00);
            shipCostLabel.setText(String.format("Shipping Cost: $%.2f", cart.getShipCost()));
            grandTotalLabel.setText(String.format("Total:     $%.2f", cart.calcGrandTotal()));
        }
        
    }//GEN-LAST:event_shippingComboBoxActionPerformed

    private void orderCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCancelButtonActionPerformed
        // TODO add your handling code here:
        //Cancel the order so clear everything out and return to home page
    }//GEN-LAST:event_orderCancelButtonActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
        //Place the order and add to the database
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void feedbackSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackSubmitButtonActionPerformed
        // TODO add your handling code here:
        //Submit feedback from user
    }//GEN-LAST:event_feedbackSubmitButtonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        //Go to correct category browsing based off combo box selection
        String selectedPage = (String)categoryComboBox.getSelectedItem();
        
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        cl.show(middlePanel, "productsCard");
        
        productViewPanel.removeAll(); //clear everything from panel from possible previous browse
        JPanel viewPanel = new JPanel();
        viewPanel.setSize(productViewPanel.getWidth(), productViewPanel.getHeight());
        viewPanel.setLayout(new BoxLayout(viewPanel, BoxLayout.Y_AXIS));
        JScrollPane scrollpanel = new JScrollPane(); //Scrollpanel so can see all products shown
        scrollpanel.setSize(productViewPanel.getWidth(), productViewPanel.getHeight());
        
        JLabel header = new JLabel();
        header.setFont(new Font("Tahoma", Font.BOLD, 20));
        viewPanel.add(header);

        //For each product matching selected category, create and add new product panel with info
        if (selectedPage.equals("All"))
        {
            header.setText("ALL");
            List<Inventory> browsedProducts = eManager.getAllProducts(); //Get list of products to browse
            ListIterator iter = browsedProducts.listIterator();
            
            while (iter.hasNext())
            {
                Inventory product = (Inventory) iter.next();
                viewPanel.add(new ProductPanel(product));
            }
        }
        
        else if (selectedPage.equals("Home"))
        {
            header.setText("HOME");
            List<Inventory> browsedProducts = eManager.getProductsByCategory(selectedPage); //Get list of products to browse
            ListIterator iter = browsedProducts.listIterator();

            while (iter.hasNext())
            {
                Inventory product = (Inventory) iter.next();
                viewPanel.add(new ProductPanel(product));
            }  
        }
        
        else if (selectedPage.equals("Clothes"))
        {
            header.setText("CLOTHES");
            selectedPage = "Apparel";
            List<Inventory> browsedProducts = eManager.getProductsByCategory(selectedPage); //Get list of products to browse
            ListIterator iter = browsedProducts.listIterator();

            while (iter.hasNext())
            {
                Inventory product = (Inventory) iter.next();
                viewPanel.add(new ProductPanel(product));
            }    
        }
        
        else if (selectedPage.equals("Kitchen"))
        {
            //No kitchen stuff to search yet
            //Add option for if no results returned
        }
        scrollpanel.setViewportView(viewPanel);
        productViewPanel.add(scrollpanel);
        productViewPanel.revalidate();
        productViewPanel.repaint();
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    
    public static void setUser(Account aUser)
    {
        user = aUser;
    }
    
    public static void clearCart()
    {
        cart.clear();
    }
    
   
    public static ShoppingCart getCart()
    {
        return cart;
    }
    
    public static AddToCartPopUp getCartPopUp()
    {
        return addCart;
    }
    
    public static CheckReviewsPopUp getReviewsPopUp()
    {
        return checkReviews;
    }
    
    public void changeHeader()
    {
        HeaderPanel.setNumInCartLabel(cart.getNumItems());
    }
    
    public static void addToCartList(ShoppingCartItem item)
    {
        Object[] data = {item.getProduct().getItemName(), item.getQuantity(), item.getProduct().getItemPrice(), item.getProduct().getItemPrice() * item.getQuantity(), false};
        cartModel.addRow(data);
            
    }
    
    public static LacysEntityManager getEManager()
    {
        return eManager;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cartPanel;
    private javax.swing.JTable cartTable;
    private javax.swing.JLabel categoryBoxLabel;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton createButton;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JButton feedbackSubmitButton;
    private javax.swing.JTextArea feedbackText;
    private javax.swing.JLabel grandTotalLabel;
    private lacysKioskGUIparts.HeaderPanel headerPanel2;
    private javax.swing.JPanel homePagePanel;
    private javax.swing.JTextArea itemsTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel leftSidePanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JLabel newAccountLabel;
    private javax.swing.JPanel newAccountPanel;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel newPasswordLabel2;
    private javax.swing.JPasswordField newPasswordText;
    private javax.swing.JPasswordField newPasswordText2;
    private javax.swing.JLabel newUsernameLabel;
    private javax.swing.JTextField newUsernameText;
    private javax.swing.JButton orderCancelButton;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JLabel pagesBoxLabel;
    private javax.swing.JComboBox pagesComboBox;
    private javax.swing.JLabel pagesLabel;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JPanel productViewPanel;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JLabel shipCostLabel;
    private javax.swing.JComboBox shippingComboBox;
    private javax.swing.JLabel shoppingLabel;
    private javax.swing.JLabel storeNameLabel;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel taxesLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
