
package lacysKioskGUIparts;

import java.awt.CardLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import lacysKioskLogicparts.LacysEntityManager;
import lacysKioskLogicparts.Messages;
import lacysKioskLogicparts.OrderDetails;
import lacysKioskLogicparts.Orders;
import lacysKioskLogicparts.Products;
import lacysKioskLogicparts.ShoppingCart;
import lacysKioskLogicparts.ShoppingCartItem;
import lacysKioskLogicparts.Users;

/**
 * Main GUI
 * Right now there's some methods and attributes in here that should probably be in a separate class
 * @author Alisha
 */
public class MainPage extends javax.swing.JFrame {

    public static final String JDBC_DRIVER = "org.sqlite.JDBC";
    public static final String DATABASE_URL = "jdbc:sqlite:C:\\Data\\Lacys";
    private static Users currentUser = null; //Holds the current user in the system
    private static ShoppingCart cart = new ShoppingCart();  //Holds shopping cart for user
    private static DefaultTableModel cartModel; //This is the model to go with the cart table
    private static AddToCartPopUp addCart; //This popup window confirms adding an item to cart
    private static CheckReviewsPopUp checkReviews; //This popup window shows product reviews
    private static ProductUpdatePopUp productUpdate; //This pop up windows allows admins to update product information
    private static ReviewPopUp writeReview; 
    private static LacysEntityManager eManager; //Class to handle inventory requests
    
   
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        eManager = new LacysEntityManager();
        cartModel = (DefaultTableModel)cartTable.getModel();
        addCart = new AddToCartPopUp();
        checkReviews = new CheckReviewsPopUp();
        productUpdate = new ProductUpdatePopUp();
        writeReview = new ReviewPopUp();
       
        desktop.add(addCart);
        desktop.add(checkReviews);
        desktop.add(productUpdate);
       desktop.add(writeReview);
       
        setProductButtons(false);
        //addProductButton.setVisible(false);
        //mainPageButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        leftSidePanel = new javax.swing.JPanel();
        pagesLabel = new javax.swing.JLabel();
        pagesBoxLabel = new javax.swing.JLabel();
        pagesComboBox = new javax.swing.JComboBox();
        addProductButton = new javax.swing.JButton();
        mainPageButton = new javax.swing.JButton();
        rightSidePanel = new javax.swing.JPanel();
        shoppingLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        categoryBoxLabel = new javax.swing.JLabel();
        middlePanel = new javax.swing.JPanel();
        homePagePanel = new javax.swing.JPanel();
        storeNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackText = new javax.swing.JTextArea();
        feedbackSubmitButton = new javax.swing.JButton();
        feedbackLabel = new javax.swing.JLabel();
        productViewPanel = new javax.swing.JPanel();
        newAccountPanel = new javax.swing.JPanel();
        newAccountLabel = new javax.swing.JLabel();
        newUsernameLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel2 = new javax.swing.JLabel();
        newUsernameText = new javax.swing.JTextField();
        newPasswordText = new javax.swing.JPasswordField();
        newPasswordText2 = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        cartPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        checkOutButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        orderPanel = new javax.swing.JPanel();
        orderLabel = new javax.swing.JLabel();
        shippingComboBox = new javax.swing.JComboBox();
        subTotalLabel = new javax.swing.JLabel();
        shipCostLabel = new javax.swing.JLabel();
        taxesLabel = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ccTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        expDateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        orderCancelButton = new javax.swing.JButton();
        custNameTextField = new javax.swing.JTextField();
        streetAddressTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        zipTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemsTextArea = new javax.swing.JTextArea();
        adminMainPage = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        adminTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        viewCustomersButton = new javax.swing.JButton();
        viewOrdersButton = new javax.swing.JButton();
        viewMessagesButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        headerPanel2 = new lacysKioskGUIparts.HeaderPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lacy's Kiosk Application");

        leftSidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        leftSidePanel.setMaximumSize(new java.awt.Dimension(300, 32767));
        leftSidePanel.setPreferredSize(new java.awt.Dimension(125, 458));

        pagesLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pagesLabel.setText("Pages");

        pagesBoxLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pagesBoxLabel.setText("Go To:");

        pagesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main", "Create Account", "My Cart" }));
        pagesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesComboBoxActionPerformed(evt);
            }
        });

        addProductButton.setText("Add Product");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        mainPageButton.setText("Main Page");
        mainPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePanelLayout = new javax.swing.GroupLayout(leftSidePanel);
        leftSidePanel.setLayout(leftSidePanelLayout);
        leftSidePanelLayout.setHorizontalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftSidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftSidePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagesBoxLabel)
                            .addComponent(pagesLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftSidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pagesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, leftSidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        leftSidePanelLayout.setVerticalGroup(
            leftSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(pagesLabel)
                .addGap(18, 18, 18)
                .addComponent(pagesBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pagesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightSidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rightSidePanel.setMaximumSize(new java.awt.Dimension(300, 32767));

        shoppingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        shoppingLabel.setText("Shopping");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Home", "Clothes", "Kitchen" }));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        categoryBoxLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        categoryBoxLabel.setText("Browse Category:");

        javax.swing.GroupLayout rightSidePanelLayout = new javax.swing.GroupLayout(rightSidePanel);
        rightSidePanel.setLayout(rightSidePanelLayout);
        rightSidePanelLayout.setHorizontalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightSidePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categoryBoxLabel))
                    .addGroup(rightSidePanelLayout.createSequentialGroup()
                        .addGroup(rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rightSidePanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(shoppingLabel))
                            .addGroup(rightSidePanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightSidePanelLayout.setVerticalGroup(
            rightSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightSidePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(shoppingLabel)
                .addGap(28, 28, 28)
                .addComponent(categoryBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        middlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        middlePanel.setPreferredSize(new java.awt.Dimension(438, 458));
        middlePanel.setLayout(new java.awt.CardLayout());

        storeNameLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 60)); // NOI18N
        storeNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        storeNameLabel.setText("Lacy's");
        storeNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        storeNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("image goes here");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("image goes here");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackText.setColumns(20);
        feedbackText.setRows(5);
        jScrollPane1.setViewportView(feedbackText);

        feedbackSubmitButton.setText("Submit");
        feedbackSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackSubmitButtonActionPerformed(evt);
            }
        });

        feedbackLabel.setLabelFor(feedbackText);
        feedbackLabel.setText("Provide Feedback: ");

        javax.swing.GroupLayout homePagePanelLayout = new javax.swing.GroupLayout(homePagePanel);
        homePagePanel.setLayout(homePagePanelLayout);
        homePagePanelLayout.setHorizontalGroup(
            homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePagePanelLayout.createSequentialGroup()
                .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePagePanelLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(feedbackSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePagePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedbackLabel)
                            .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(homePagePanelLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addComponent(storeNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        homePagePanelLayout.setVerticalGroup(
            homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePagePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(storeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(feedbackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedbackSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        middlePanel.add(homePagePanel, "homePanelCard");

        javax.swing.GroupLayout productViewPanelLayout = new javax.swing.GroupLayout(productViewPanel);
        productViewPanel.setLayout(productViewPanelLayout);
        productViewPanelLayout.setHorizontalGroup(
            productViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        productViewPanelLayout.setVerticalGroup(
            productViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        middlePanel.add(productViewPanel, "productsCard");

        newAccountLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        newAccountLabel.setText("New Account");

        newUsernameLabel.setLabelFor(newUsernameText);
        newUsernameLabel.setText("Enter Username: ");

        newPasswordLabel.setLabelFor(newPasswordText);
        newPasswordLabel.setText("Enter Password: ");

        newPasswordLabel2.setLabelFor(newPasswordText2);
        newPasswordLabel2.setText("Re-enter Password:");

        createButton.setText("Create Account");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newAccountPanelLayout = new javax.swing.GroupLayout(newAccountPanel);
        newAccountPanel.setLayout(newAccountPanelLayout);
        newAccountPanelLayout.setHorizontalGroup(
            newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAccountPanelLayout.createSequentialGroup()
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAccountPanelLayout.createSequentialGroup()
                        .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAccountPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(newUsernameLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(newPasswordLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createButton)
                            .addComponent(newUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newPasswordText2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newAccountPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(newPasswordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newAccountPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(newAccountLabel)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        newAccountPanelLayout.setVerticalGroup(
            newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAccountPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(newAccountLabel)
                .addGap(52, 52, 52)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUsernameLabel)
                    .addComponent(newUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLabel))
                .addGap(46, 46, 46)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPasswordLabel2))
                .addGap(42, 42, 42)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        middlePanel.add(newAccountPanel, "newAccountCard");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("My Cart");

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Price", "Total", "Remove"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setName(""); // NOI18N
        jScrollPane2.setViewportView(cartTable);

        checkOutButton.setText("Check Out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Cart");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalLabel.setText("Total: $##.##");

        updateButton.setText("Update Cart");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cartPanelLayout = new javax.swing.GroupLayout(cartPanel);
        cartPanel.setLayout(cartPanelLayout);
        cartPanelLayout.setHorizontalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton))
                    .addGroup(cartPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(totalLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(checkOutButton)
                .addGap(44, 44, 44)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartPanelLayout.setVerticalGroup(
            cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addGap(18, 18, 18)
                .addGroup(cartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkOutButton)
                    .addComponent(clearButton))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        middlePanel.add(cartPanel, "cartCard");

        orderPanel.setPreferredSize(new java.awt.Dimension(432, 458));

        orderLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        orderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderLabel.setText("Order");

        shippingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Add Shipping", "Ship to Store - Free", "Ship to Home - $10.00" }));
        shippingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingComboBoxActionPerformed(evt);
            }
        });

        subTotalLabel.setText("Subtotal: $#.##");

        shipCostLabel.setText("Shipping: $#.##");

        taxesLabel.setText("Taxes: $#.##");

        grandTotalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grandTotalLabel.setText("Total: $#.##");

        jLabel8.setText("Credit card number:");

        jLabel9.setText("Expiration date: ");

        expDateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        expDateTextField.setText("xx/xxxx");

        jLabel10.setText("Enter name: ");

        jLabel11.setText("Enter street address:");

        jLabel12.setText("Enter city:");

        jLabel13.setText("Enter state:");

        jLabel14.setText("Enter Zip Code:");

        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderButtonActionPerformed(evt);
            }
        });

        orderCancelButton.setText("Cancel");
        orderCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCancelButtonActionPerformed(evt);
            }
        });

        itemsTextArea.setColumns(20);
        itemsTextArea.setRows(5);
        jScrollPane3.setViewportView(itemsTextArea);

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(orderLabel))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(placeOrderButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(custNameTextField))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(streetAddressTextField)))))
                .addContainerGap())
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(taxesLabel)
                                    .addComponent(subTotalLabel)
                                    .addComponent(shipCostLabel)
                                    .addComponent(grandTotalLabel)))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(shippingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ccTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cityTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stateTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderCancelButton)
                                    .addGroup(orderPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shippingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shipCostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grandTotalLabel)
                .addGap(18, 18, 18)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(expDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(streetAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeOrderButton)
                    .addComponent(orderCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        middlePanel.add(orderPanel, "orderCard");

        adminTextArea.setEditable(false);
        adminTextArea.setColumns(20);
        adminTextArea.setRows(5);
        adminTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(adminTextArea);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Admin Home Page");

        viewCustomersButton.setText("View Customers");
        viewCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersButtonActionPerformed(evt);
            }
        });

        viewOrdersButton.setText("View Orders");
        viewOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersButtonActionPerformed(evt);
            }
        });

        viewMessagesButton.setText("View Messages");
        viewMessagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMessagesButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Choose an option to view:");

        javax.swing.GroupLayout adminMainPageLayout = new javax.swing.GroupLayout(adminMainPage);
        adminMainPage.setLayout(adminMainPageLayout);
        adminMainPageLayout.setHorizontalGroup(
            adminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMainPageLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(viewCustomersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewOrdersButton)
                .addGap(55, 55, 55)
                .addComponent(viewMessagesButton)
                .addGap(38, 38, 38))
            .addGroup(adminMainPageLayout.createSequentialGroup()
                .addGroup(adminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminMainPageLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(adminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(adminMainPageLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        adminMainPageLayout.setVerticalGroup(
            adminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminMainPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addGroup(adminMainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCustomersButton)
                    .addComponent(viewOrdersButton)
                    .addComponent(viewMessagesButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        middlePanel.add(adminMainPage, "adminCard");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addComponent(leftSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(middlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(leftSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addComponent(rightSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        desktop.setLayer(leftSidePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(rightSidePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(middlePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(headerPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pagesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesComboBoxActionPerformed
        //From the combo box on the left, go to specific pages/cards in card layout of middle panel
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        String selectedPage = (String)pagesComboBox.getSelectedItem();
        
        if (selectedPage.equals("Main"))
        {
            cl.show(middlePanel, "homePanelCard");
        }
        else if (selectedPage.equals("Create Account"))
        {
            cl.show(middlePanel, "newAccountCard");
        }
        else if (selectedPage.equals("My Cart"))
        {
            cl.show(middlePanel, "cartCard");
            totalLabel.setText(String.format("Total: $%,.2f", cart.getTotal()));
            changeHeader();
        }
        
    }//GEN-LAST:event_pagesComboBoxActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        //When click check out button, go to check out page/card
        boolean completeCheckOut = true;
        
        if (currentUser == null)
        {
            int option = JOptionPane.showConfirmDialog(null, "No user is logged in. Continue as a guest or select Cancel to log in above.",
                        "No current user", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION)
            {
                Users tempUser = eManager.findUser("Guest");
                setUser(tempUser);
            }
            else
            {
                completeCheckOut = false;
            }
        }
        
        if (completeCheckOut)
        {
            CardLayout cl = (CardLayout)(middlePanel.getLayout());
            cl.show(middlePanel, "orderCard");
        
            String orderText = "";
            orderText = "        Item Name                    Quantity        Price           Total Price\n";
            orderText += "-----------------------------------  -------------     -----------     -----------------\n";
            for (int i = 0; i < cartModel.getRowCount (); i++)
            {
                String name = cartModel.getValueAt(i, 0).toString();
                int amount = (int) cartModel.getValueAt(i, 1);
                double price = (double) cartModel.getValueAt(i, 2);
                orderText += String.format("%-45s  %-16d  $%-12.2f  %-12.2f\n", name, amount, price, amount * price);
            }
            itemsTextArea.setText(orderText);
            shippingComboBox.setSelectedIndex(0);
            subTotalLabel.setText(String.format("Subtotal: $%.2f", cart.getTotal()));
            taxesLabel.setText(String.format("Sales Tax: $%.2f", cart.getTotal() * cart.getSalesTax()));  //Hard coded sales tax rate in
            shipCostLabel.setText(String.format("Shipping Cost: $%.2f", 0.00));
            grandTotalLabel.setText(String.format("Total:     $%.2f", cart.calcGrandTotal()));
            cart.setShipCost(0.00);
        }
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        //Go through actions to create new user and add to database
        boolean created = false;
        if (newUsernameText.getText().trim().isEmpty() || newPasswordText.getPassword().length == 0 || newPasswordText2.getPassword().length == 0)
        {
            JOptionPane.showMessageDialog(null, "All fields must be entered", "No blank fields", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String username = newUsernameText.getText();
            String password = String.valueOf(newPasswordText.getPassword());
            String password2 = String.valueOf(newPasswordText2.getPassword());
            
            Users tempUser = eManager.findUser(username);
            if (tempUser == null) //Don't want to find a user with that name since would mean is already taken
            {
                if (password.equals(password2))
                {
                    eManager.addCustomer(username, password);
                    JOptionPane.showMessageDialog(null, "User account has been created.", "Account created.", JOptionPane.OK_OPTION);
                    created = true;
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password fields don't match.", "Mismatched passwords", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "That username already exists in the database.", "Username taken", JOptionPane.ERROR_MESSAGE);
            }
        }
       
        newUsernameText.setText("");
        newPasswordText.setText("");
        newPasswordText2.setText("");
        
        if (created)
        {
            CardLayout cl = (CardLayout)(middlePanel.getLayout());
            cl.show(middlePanel, "homePanelCard");
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        //Checks if any checkboxes are checked or unchecked and then deletes the ones
        //that are checked from cart
        ArrayList<Integer> rowNums = new ArrayList<Integer>(); //holds row numbers that need to be deleted
        int numRows = cartModel.getRowCount();
        for (int row = 0; row < numRows; row++)
        {
            String prodName = cartModel.getValueAt(row, 0).toString();
            Products product = eManager.findProductbyName(prodName);
            if ((boolean) cartModel.getValueAt(row, 4) || (int) cartModel.getValueAt(row, 1) == 0)
            {
                //remove row from cart table list and cart map
                if (product != null)
                {
                    cart.removeItem(product.getProductID());
                    //cartModel.removeRow(row);
                    rowNums.add(row);
                }
            }
            else
            {
                //get object info from cart and update cart map
                if (product != null)
                {
                    cart.updateItem(product.getProductID(), (int) cartModel.getValueAt(row, 1));
                    cartModel.setValueAt((int) cartModel.getValueAt(row, 1) * (double) cartModel.getValueAt(row, 2) , row, 3);
                }
            }
        }
        
        //Go backwards so if deleting multiple rows from table, it won't affect later row numbers
        for (int i = rowNums.size() - 1; i >= 0; i--)  
        {
            cartModel.removeRow(rowNums.get(i));
        }
        cartModel.fireTableDataChanged();
        totalLabel.setText(String.format("Total: $%,.2f", cart.getTotal()));
        changeHeader();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        //This button will clear all the items currently in the cart and return to the home page maybe?
        int numRows = cartModel.getRowCount();
        for (int i = numRows - 1; i >= 0; i--)
        {   
            cartModel.removeRow(i);
        }
        cartModel.fireTableDataChanged();
        cart.clear();
        totalLabel.setText(String.format("Total: $%,.2f", cart.getTotal()));
        changeHeader();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void shippingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingComboBoxActionPerformed
        String shipChoice = shippingComboBox.getSelectedItem().toString();
        if (shipChoice.equals("Ship to Store - Free"))
        {
            cart.setShipCost(0.00);
            shipCostLabel.setText(String.format("Shipping Cost: $%.2f", cart.getShipCost()));
            grandTotalLabel.setText(String.format("Total:     $%.2f", cart.calcGrandTotal()));
        }
        else if (shipChoice.equals("Ship to Home - $10.00"))
        {
            cart.setShipCost(10.00);
            shipCostLabel.setText(String.format("Shipping Cost: $%.2f", cart.getShipCost()));
            grandTotalLabel.setText(String.format("Total:     $%.2f", cart.calcGrandTotal()));
        }
        
    }//GEN-LAST:event_shippingComboBoxActionPerformed

    private void orderCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCancelButtonActionPerformed
        //Cancel the order so clear everything out and return to home page
        
        shippingComboBox.setSelectedIndex(0);
        ccTextField.setText("");
        expDateTextField.setText("");
        custNameTextField.setText("");
        streetAddressTextField.setText("");
        cityTextField.setText("");
        stateTextField.setText("");
        zipTextField.setText("");
        
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        cl.show(middlePanel, "homePanelCard");
        
        if (currentUser.getUserName().equals("Guest"))
            currentUser = null;
        
    }//GEN-LAST:event_orderCancelButtonActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        //Place the order and add to the database
        if (haveEmptyFields())
        {
            JOptionPane.showMessageDialog(null, "All text fields must be entered for order information.", "Empty Fields", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String address = String.format("%s, %s, %s, %s", streetAddressTextField.getText().trim(),
                                                            cityTextField.getText().trim(),
                                                            stateTextField.getText().trim(),
                                                            zipTextField.getText().trim());
            eManager.addOrder(cart, address);
            
            shippingComboBox.setSelectedIndex(0);
            ccTextField.setText("");
            expDateTextField.setText("");
            custNameTextField.setText("");
            streetAddressTextField.setText("");
            cityTextField.setText("");
            stateTextField.setText("");
            zipTextField.setText("");
            clearCart();
            changeHeader();
        
            JOptionPane.showMessageDialog(null, "Your order has been placed.", "Order complete", JOptionPane.INFORMATION_MESSAGE);
            CardLayout cl = (CardLayout)(middlePanel.getLayout());
            cl.show(middlePanel, "homePanelCard");
            
            if (currentUser.getUserName().equals("Guest"))
                currentUser = null;
        }
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void feedbackSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackSubmitButtonActionPerformed
        //Submit feedback from user
        if (currentUser == null)
        {
            JOptionPane.showMessageDialog(null, "You must be logged in to submit feedback.", "Feedback Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (feedbackText.getText().trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "You must enter a message to submit.", "Feedback Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String text = feedbackText.getText();
            eManager.addFeedback(text);
        }
    }//GEN-LAST:event_feedbackSubmitButtonActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        //Go to correct category browsing based off combo box selection
        String selectedPage = (String)categoryComboBox.getSelectedItem();
        
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        cl.show(middlePanel, "productsCard");
        
        productViewPanel.removeAll(); //clear everything from panel from possible previous browse
        JPanel viewPanel = new JPanel();
        viewPanel.setSize(productViewPanel.getWidth(), productViewPanel.getHeight());
        viewPanel.setLayout(new BoxLayout(viewPanel, BoxLayout.Y_AXIS));
        JScrollPane scrollpanel = new JScrollPane(); //Scrollpanel so can see all products shown
        scrollpanel.setSize(productViewPanel.getWidth(), productViewPanel.getHeight());
        
        JLabel header = new JLabel();
        header.setFont(new Font("Tahoma", Font.BOLD, 20));
        viewPanel.add(header);
        
        List<Products> browsedProducts;

        //For each product matching selected category, create and add new product panel with info
        if (selectedPage.equals("All"))
        {
            header.setText("ALL");
        }
        
        else if (selectedPage.equals("Home"))
        {
            header.setText("HOME");
        }
        
        else if (selectedPage.equals("Clothes"))
        {
            header.setText("CLOTHES");
        }
        
        else if (selectedPage.equals("Kitchen"))
        {
            header.setText("KITCHEN");
        }
        
        if (selectedPage.equals("All"))
            browsedProducts = eManager.getAllProducts();
        else
            browsedProducts = eManager.getProductsByCategory(selectedPage); //Get list of products to browse
        ListIterator iter = browsedProducts.listIterator();

        while (iter.hasNext())
        {
            Products product = (Products) iter.next();
            if (currentUser == null || currentUser.getUserPrivilege().equals("Customer"))
                viewPanel.add(new ProductPanel(product));
            else if (currentUser.getUserPrivilege().equals("Admin"))
                viewPanel.add(new AdminProductPanel(product));
        }    
        
        
        scrollpanel.setViewportView(viewPanel);
        productViewPanel.add(scrollpanel);
        productViewPanel.revalidate();
        productViewPanel.repaint();
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void mainPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageButtonActionPerformed
        CardLayout cl = (CardLayout)(middlePanel.getLayout());
        cl.show(middlePanel, "adminCard");
        adminTextArea.setText("");

    }//GEN-LAST:event_mainPageButtonActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        productUpdate.setUpUpdatePopUp();
        productUpdate.setVisible(true);
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void viewCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCustomersButtonActionPerformed

    private void viewOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersButtonActionPerformed
        // TODO add your handling code here:
        List<Orders> allOrders = eManager.getAllOrders();
        String message = "";
        for (Orders order : allOrders)
        {
            message += String.format("Order ID: %d, User ID: %d, Destination: %s\n", order.getOrderID(), order.getUserID().getUserID(),
                    order.getDestination());
            Collection<OrderDetails> details = order.getOrderDetailsCollection();
            Iterator iter = details.iterator();
            while (iter.hasNext())
            {
                OrderDetails detail = (OrderDetails) iter.next();
                message += detail.toString();
                message += "\n";
            }
            message += "\n\n";
            adminTextArea.setText("");
            adminTextArea.setText(message);
            
        }
        
    }//GEN-LAST:event_viewOrdersButtonActionPerformed

    private void viewMessagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMessagesButtonActionPerformed
        // TODO add your handling code here:
        List<Messages> allMessages = eManager.getAllStoreMessages();
        
        String messageText = "";
        for (int i = 0; i < allMessages.size(); i++)
        {
            Messages message = allMessages.get(i);
            messageText += String.format("Message ID: %d\n", message.getMessageID());
            messageText += String.format("Message Type: %s\n", message.getMessageType());
            messageText += String.format("Username: %s\n", message.getUserID().getUserName());
            messageText += String.format("Contents: %s\n", message.getContents());
            messageText += "--------------------------------------------------------------------\n\n\n";
        }
        adminTextArea.setText(messageText);
    }//GEN-LAST:event_viewMessagesButtonActionPerformed

    
    public static void setUser(Users aUser)
    {
        currentUser = aUser;
    }
    
    public static Users getUser()
    {
        return currentUser;
    }
    
    public static void clearCart()
    {
        cart.clear();
    }
    
   
    public static ShoppingCart getCart()
    {
        return cart;
    }
    
    public static AddToCartPopUp getCartPopUp()
    {
        return addCart;
    }
    
    public static CheckReviewsPopUp getReviewsPopUp()
    {
        return checkReviews;
    }
    
    public static ProductUpdatePopUp getUpdatePopUp()
    {
        return productUpdate;
    }
    
    public static ReviewPopUp getReviewPopUp()
    {
        return writeReview;
    }
    
    public void changeHeader()
    {
        HeaderPanel.setNumInCartLabel(cart.getNumItems());
    }
    
    public static void addToCartList(ShoppingCartItem item)
    {
        Object[] data = {item.getProduct().getProductName(), item.getQuantity(), item.getProduct().getUnitPrice(), item.getProduct().getUnitPrice() * item.getQuantity(), false};
        cartModel.addRow(data);
            
    }
    
    public static LacysEntityManager getEManager()
    {
        return eManager;
    }
    
    public static void setProductButtons(boolean isLoggedIn)
    {
        if (isLoggedIn && currentUser.getUserPrivilege().equals("Admin"))
        {
            addProductButton.setVisible(true);
            mainPageButton.setVisible(true);
            pagesLabel.setVisible(false);
            pagesComboBox.setVisible(false);
        }
        else
        {
            addProductButton.setVisible(false);
            mainPageButton.setVisible(false);
            pagesLabel.setVisible(true);
            pagesComboBox.setVisible(true);
        }
    }
    
  
    
    public boolean haveEmptyFields()
    {
        boolean empty = false;
        
        if (ccTextField.getText().trim().equals(""))
            empty = true;
        else if (expDateTextField.getText().trim().equals(""))
            empty = true;
        else if (custNameTextField.getText().trim().equals(""))
            empty = true;
        else if (streetAddressTextField.getText().trim().equals(""))
            empty = true;
        else if (cityTextField.getText().trim().equals(""))
            empty = true;
        else if (stateTextField.getText().trim().equals(""))
            empty = true;  
        else if (zipTextField.getText().trim().equals(""))
            empty = true;        
        
        return empty;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton addProductButton;
    private javax.swing.JPanel adminMainPage;
    private javax.swing.JTextArea adminTextArea;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JTable cartTable;
    private javax.swing.JLabel categoryBoxLabel;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JTextField ccTextField;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JTextField expDateTextField;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JButton feedbackSubmitButton;
    private javax.swing.JTextArea feedbackText;
    private javax.swing.JLabel grandTotalLabel;
    private lacysKioskGUIparts.HeaderPanel headerPanel2;
    private javax.swing.JPanel homePagePanel;
    private javax.swing.JTextArea itemsTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel leftSidePanel;
    private static javax.swing.JButton mainPageButton;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JLabel newAccountLabel;
    private javax.swing.JPanel newAccountPanel;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel newPasswordLabel2;
    private javax.swing.JPasswordField newPasswordText;
    private javax.swing.JPasswordField newPasswordText2;
    private javax.swing.JLabel newUsernameLabel;
    private javax.swing.JTextField newUsernameText;
    private javax.swing.JButton orderCancelButton;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JLabel pagesBoxLabel;
    private static javax.swing.JComboBox pagesComboBox;
    private static javax.swing.JLabel pagesLabel;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JPanel productViewPanel;
    private javax.swing.JPanel rightSidePanel;
    private javax.swing.JLabel shipCostLabel;
    private javax.swing.JComboBox shippingComboBox;
    private javax.swing.JLabel shoppingLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JLabel storeNameLabel;
    private javax.swing.JTextField streetAddressTextField;
    private javax.swing.JLabel subTotalLabel;
    private javax.swing.JLabel taxesLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton viewCustomersButton;
    private javax.swing.JButton viewMessagesButton;
    private javax.swing.JButton viewOrdersButton;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
