
package lacysKioskGUIparts;

import lacysKioskLogicparts.Products;

/**
 * Internal frame pop up window to update product info
 * @author Alisha
 */
public class ProductUpdatePopUp extends javax.swing.JInternalFrame {
   
    Products product;
    boolean add = false; //if adding new product, this will become true
    
    /**
     * Creates new form ProductUpdatePopUp
     */
    public ProductUpdatePopUp() {
        initComponents();
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminDescriptionTxtField = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        updateCancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        adminProductTxtField = new javax.swing.JTextField();
        adminPriceTxtField = new javax.swing.JTextField();
        adminQuantityTxtField = new javax.swing.JTextField();
        categoryComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        itemIDTxtField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();

        jLabel1.setText("Item Name:");

        jLabel2.setText("Item Price:");

        jLabel3.setText("Item Quantity:");

        adminDescriptionTxtField.setColumns(20);
        adminDescriptionTxtField.setRows(5);
        jScrollPane1.setViewportView(adminDescriptionTxtField);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        updateCancelButton.setText("Cancel");
        updateCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Details:");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Category:", "Home", "Clothes", "Kitchen" }));

        jLabel5.setText("Item ID");

        itemIDTxtField.setEditable(false);
        itemIDTxtField.setEnabled(false);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(adminPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(adminQuantityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(itemIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(131, 131, 131)
                                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(adminProductTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateButton)
                        .addGap(35, 35, 35)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(updateCancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adminProductTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminQuantityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(resetButton)
                    .addComponent(updateCancelButton)
                    .addComponent(deleteButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String name = adminProductTxtField.getText().trim();
        Double price = Double.parseDouble(adminPriceTxtField.getText().trim());
        Integer amount = Integer.parseInt(adminQuantityTxtField.getText().trim());
        String desc = adminDescriptionTxtField.getText().trim();
        String category = (String) categoryComboBox.getSelectedItem();
        
        Products updatedProduct = new Products(name, price, amount, 0, category, desc, 0.0);
        
        if (add)
            MainPage.getEManager().addProduct(updatedProduct);
        else
        {
            updatedProduct.setProductID(product.getProductID());
            MainPage.getEManager().updateProduct(updatedProduct);
        }
        setVisible(false);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        setUpUpdatePopUp(product);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        MainPage.getEManager().deleteProduct(product);
        setVisible(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_updateCancelButtonActionPerformed

    public void setUpUpdatePopUp(Products product) //Set up pop up when updating or deleting a current product
    {
        add = false;
        this.product = product;
        itemIDTxtField.setText(product.getProductID().toString());
        adminProductTxtField.setText(product.getProductName());
        adminPriceTxtField.setText(product.getUnitPrice().toString());
        adminQuantityTxtField.setText(product.getUnitsInStock().toString());
        adminDescriptionTxtField.setText(product.getDescription());
        categoryComboBox.setSelectedItem(product.getCategory());
        deleteButton.setEnabled(true);
        updateButton.setText("Update");
    }
    
    public void setUpUpdatePopUp() //Set up pop up when adding completely new product
    { 
        add = true;
        this.product = null;
        itemIDTxtField.setText("");
        adminProductTxtField.setText("");
        adminPriceTxtField.setText("");
        adminQuantityTxtField.setText("");
        adminDescriptionTxtField.setText("");
        categoryComboBox.setSelectedIndex(0);
        deleteButton.setEnabled(false);
        updateButton.setText("Add");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adminDescriptionTxtField;
    private javax.swing.JTextField adminPriceTxtField;
    private javax.swing.JTextField adminProductTxtField;
    private javax.swing.JTextField adminQuantityTxtField;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField itemIDTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateCancelButton;
    // End of variables declaration//GEN-END:variables
}
